 <div class="foot" >
   <div>
     <a href="<%=HostApi.MGetIndexHref() %>">网站首页
     </a>
   </div>

   <div>
     <asp:Literal ID="llFootInfo" runat="server"></asp:Literal>
   <a href="<%=IISPath %>">电脑版</a>  |  <a href="<%=HostApi.MGetIndexHref() %>">移动版</a>
   </div>
   <div style="display:none">
         <script src="http://s19.cnzz.com/stat.php?id=1460745&web_id=1460745" language="JavaScript"></script>
   </div>
 </div>