//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4200
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbSite.Install
{
    
    
    public partial class step3 {

        protected global::System.Web.UI.WebControls.Panel PanelErr;

        protected global::System.Web.UI.WebControls.Panel PanelOK;
        /// <summary>
        /// Form1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// llTitle 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal llTitle;
        
        /// <summary>
        /// msg 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal msg;
        
        /// <summary>
        /// ddlDbType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::EbSite.Control.DropDownList ddlDbType;
        
        /// <summary>
        /// txtDatasource 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::EbSite.Control.TextBox txtDatasource;
        
        /// <summary>
        /// txtDataBaseName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::EbSite.Control.TextBox txtDataBaseName;
        
        /// <summary>
        /// txtDataBaseUser 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::EbSite.Control.TextBox txtDataBaseUser;
        
        /// <summary>
        /// txtDataBasePass 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::EbSite.Control.TextBox txtDataBasePass;
        
        /// <summary>
        /// txtTableprefix 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::EbSite.Control.TextBox txtTableprefix;
        
        /// <summary>
        /// txtAccessFileName 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::EbSite.Control.TextBox txtAccessFileName;
        
        /// <summary>
        /// bntStarInstall 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button bntStarInstall;
        
        /// <summary>
        /// cbIsOutOfUser 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbIsOutOfUser;


        protected global::EbSite.Control.TextBox txtMySqlDatasource;

       protected global::EbSite.Control.TextBox txtSport;

         protected global::EbSite.Control.TextBox   txtMySqlDataBaseName;

         protected global::EbSite.Control.TextBox   txtMySqlDataBaseUser;

          protected global::EbSite.Control.TextBox  txtMySqlDataBasePass;

          protected global::EbSite.Control.TextBox txtMySqlTableprefix;
    }
}
