#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/bbbb/Index.cshtml")]
    public partial class _Views_bbbb_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_bbbb_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(" \r\n\r\n<h2>我是bbbbbbbbbbbbbbb</h2>\r\n\r\n\r\n输出值为:\r\n");

            
            #line 7 "..\..\Views\bbbb\Index.cshtml"
Write(ViewBag.ddd);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
