//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbSite.Web.AdminHt.Controls.Admin_Special {
    
    
    public partial class MergeSpecialBak {
        
        /// <summary>
        /// Notes1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EbSite.Control.Notes Notes1;
        
        /// <summary>
        /// drpSoure control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EbSite.Control.DropDownList drpSoure;
        
        /// <summary>
        /// drpTarget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EbSite.Control.DropDownList drpTarget;
    }
}
