

  <div class="footer">
  <div class="container">

    <div class="clear"></div>
    <div class="youlian copy" style="margin:0;">
      <ul style="padding:0; margin:0">
        <%=EbSite.Base.Configs.SysConfigs.ConfigsControl.Instance.Copyright %>
      </ul>
    </div>

  </div>
</div>
 

<div style="display:none">
	<script src="http://s13.cnzz.com/stat.php?id=1724171&web_id=1724171" language="JavaScript"></script>
</div>