<div class="top">
  <div class="container" style="position:relative;">
    <div class="top_part1">
		  <div class="rukou all2pic">
			<ul>
			  <li><a href="/jingxiaoshangjiameng/" class="" >经销商加盟入口 </a></li>
			  <li><a href="/xiulichangjiameng/">修理厂加盟入口</a></li>
			</ul>
		  </div>
      
		  <div id="login_infobm" class="orther2">
			<ul>
			  <a href='<%=EbSite.Base.Host.Instance.GetLoginApiUrl("SINA")%>'> <div class="sinalogin all2pic"></div></a>
			  <a  href='<%=EbSite.Base.Host.Instance.GetLoginApiUrl("QQ")%>'> <div class="qqlogin all2pic"></div></a>
			  <li><a href="<%=EbSite.Base.Host.Instance.LoginRw %>" style="color:#076FA2" >登录</a></li>
			  <li><a href="<%=EbSite.Base.Host.Instance.RegRw %>" style="color:#FF6633">注册</a></li>  
			</ul>
		  </div>
		  
		  <div class="orther3"> 
			<ul>
			  <li class="kefu"><a href="/customercenter/"  style="color:green" target="_blank" >客服中心</a></li>
			  <li class="weibo">官方微博</li>
			</ul> 
		  </div>
   
      <div class="clear"></div>
    </div>
	
    <div class="top_part2">
      <div class="bmlogo"><a href="<%=DomainName%>"><img src="/themes/default/css/images/logo.gif"  class="logo" /></a></div>
      <div class="besttitle">中国最大汽车配件销售与修车服务平台</div>
      <div class="tel"></div>
    </div>
    <div class="clear"></div>
    <div class="top_part3">
      <ul>
        <li class="index"><a href="<%=DomainName%>">首页 </a></li>
        <li>
          <a class="dd_bg1 dd_bg11" href="/pinpaidaquan.shtml">
            从车型查找配件
          </a>
        </li>
        <li>
          <a class="dd_bg1  dd_bg10" href="/peijiandaquan.shtml">
            汽车配件大全
          </a>
        </li>
        <li>
          <a class="dd_bg1  dd_bg5" href="#">
            拆车件
          </a>
        </li>
        <li class="widthsopei">
          <a class="dd_bg1" style="width:50px;" href="/so.html">
            搜配
          </a>
        </li>
        <li>
            <a href="/wenda/index.htm" class="dd_bg1 dd_bg3">维修问答</a>
        </li>
        <li class="ks"><a href="/yuding.shtml" ><img src="/themes/default/css/images/ks.jpg" /></a></li>
        <li class="gwc" id="bm_gwc_count">0</li>
        <li class="chakan" id="bm_chakan_do"><img src="/themes/default/css/images/js.jpg" /></li>
      </ul>
    </div>
  </div>
</div>

