//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbSite.Modules.Wenda.Widgets.GetSolve {
    
    
    public partial class widget {
        
        /// <summary>
        /// ucClassData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EbSite.Modules.BmAsk.Widgets.GetSolve.Controls.GetClassDataModel ucClassData;
    }
}
