////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.3031
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace EbSite.Control.FileManager
//{
    
    
//    public partial class FileList {
        
//        /// <summary>
//        /// MainPage control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Panel MainPage;
        
//        /// <summary>
//        /// Form1 control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
//        /// <summary>
//        /// gallerymessage control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Label gallerymessage;
        
//        /// <summary>
//        /// GalleryPanel control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Panel GalleryPanel;
        
//        /// <summary>
//        /// UploadPanel control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Panel ToolBar;
        
//        /// <summary>
//        /// DeleteImage control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button DeleteImage;
        
//        /// <summary>
//        /// ResultsMessage control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Literal ResultsMessage;
        
//        /// <summary>
//        /// FileToDelete control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.HtmlControls.HtmlInputHidden FileToDelete;
        
//        /// <summary>
//        /// RootImagesFolder control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//       // protected global::System.Web.UI.HtmlControls.HtmlInputHidden RootFileFolder;
        
//        /// <summary>
//        /// CurrentImagesFolder control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//       // protected global::System.Web.UI.HtmlControls.HtmlInputHidden CurrentFileFolder;
        
//        /// <summary>
//        /// iframePanel control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Panel iframePanel;
//    }
//}
