////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.1433
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace EbSite.Control.FileManager
//{
    
    
//    public partial class UploadSingle {
        
//        /// <summary>
//        /// Head1 control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
//        /// <summary>
//        /// form1 control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
//        /// <summary>
//        /// uploadPanel control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Panel uploadPanel;
        
//        /// <summary>
//        /// fileUpload control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.FileUpload fileUpload;
        
//        /// <summary>
//        /// btnUpload control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button btnUpload;
        
//        /// <summary>
//        /// resultPanel control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Panel resultPanel;
        
//        /// <summary>
//        /// label control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Label label;

//        protected global::System.Web.UI.HtmlControls.HtmlTableCell UploadType;

//        protected global::System.Web.UI.HtmlControls.HtmlTableCell UploadSize;
        
//    }
//}
