<div class="toolbar">
  <div class="clearfix">
    <ul id="topLinks" >
      <a href="<%=HostApi.Domain %>">
        <span>首页</span>
      </a>

      <a href="<%=HostApi.MGetIndexHref() %>" target="_blank">
        <span>手机版</span>
      </a>

    </ul>
    <div id="login_info" class="userbar">
      <a href="<%=HostApi.LoginRw %>">登录
      </a>
      <a href="<%=HostApi.RegRw %>">注册
      </a>
    </div>
  </div>
</div>