#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/userinfo/Index.cshtml")]
    public partial class _Views_userinfo_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_userinfo_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\userinfo\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>我是用户资料管理页面的首页</h2>\r\n\r\n\r\n输出值为:\r\n");

            
            #line 9 "..\..\Views\userinfo\Index.cshtml"
Write(ViewBag.ddd);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<a");

WriteAttribute("href", Tuple.Create(" href=\"", 94), Tuple.Create("\"", 129)
            
            #line 12 "..\..\Views\userinfo\Index.cshtml"
, Tuple.Create(Tuple.Create("", 101), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "bbbb")
            
            #line default
            #line hidden
, 101), false)
);

WriteLiteral("> 连接到ddd</a>");

        }
    }
}
#pragma warning restore 1591
