#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/uccindex/Index.cshtml")]
    public partial class _Views_uccindex_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_uccindex_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(" \r\n\r\n");

            
            #line 3 "..\..\Views\uccindex\Index.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <title>title</title>\r\n</head>\r\n<body>\r" +
"\n<div>\r\n    uccindexuccindexuccindexuccindexuccindexuccindexuccindex\r\n</div>\r\n</" +
"body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
